swagger: '2.0'
info:
  title: 'Flasgger Parsed Method'
  version: '0.1'

parameters:
  - name: delete_by_id
    type: integer
    in: query
    required: True
    default: 1
responses:
  200:
    description: OK
